services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pipeline_net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - pipeline_net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - pipeline_net

  debezium-server:
    image: debezium/server:2.6
    container_name: debezium-server
    depends_on:
      - kafka
      - postgres
    environment:
      - TZ=UTC
    volumes:
      - ./config/debezium/application.properties:/debezium/conf/application.properties:ro
    networks:
      - pipeline_net

  airflow:
    image: apache/airflow:2.9.3
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: "somethingrandom"
      AIRFLOW__WEBSERVER__SECRET_KEY: "anothersecret"
      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-apache-kafka
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    networks:
      - pipeline_net

networks:
  pipeline_net:
    driver: bridge
